---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: others
  namespace: default
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: others-role
rules:
- apiGroups: [""] 
  resources: ["namespace"] 
  verbs: ["get","list","watch"] 
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: others-cluster-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: others 
  namespace: default
roleRef:
  kind: ClusterRole
  name: others-role 
  apiGroup: rbac.authorization.k8s.io

